### ISSUE TITLE
CudaContext created with 

### ISSUE THREAD

**Issue by dje-dev** [kunzmi/managedCuda#101]
I believe there may be a bug with this method. If called with createNew=false, the code calls cuCtxGetCurrent and returns the context if found. The problem is that the returned context might happen to be on a different deviceId from the one requested, in which case the returned CudaContext is incorrect.
```
	public CudaContext(int deviceId, bool createNew)
```

**Comment by kunzmi** [comment]
Hi, you're right, I was testing this only on a single device machine where, obviously, this cannot happen.
I'll look into it as soon as I'll find a bit of time. (while I also realized that I never pushed any CUDA updates to the repository...)

**Comment by kunzmi** [comment]
Fixed in latest commit
