### ISSUE TITLE
CudaBlas Handler Initialization Error

### ISSUE THREAD

**Issue by chenw11** [kunzmi/managedCuda#102]
Hi Kunzmi,
This maybe a very basic question. I encountered an error when trying to initializing a cublas handle using the CudaBlas wrapper. I ran into the following error when calling the cublas constructor, where it points out that the cublas64_11.dll from cuda toolbox is missing. 
![image](https://user-images.githubusercontent.com/17182101/125395782-9f69ef80-e379-11eb-86a6-496b9ab70dc4.png)
So far, I have tried downloading the latest ManagedCuda (11.1) from GitHub repository, build as 64-bit in local, then import the CudaBlas.dll (8.0.13) to my application reference. It gives a similar error but with different missing cublas dll file (cublas64_80.dll). Also I tried to download the CudaBlas packages (11.0.43) from NUGet repository, and installed using NUGet package installer. Unfortunately, it still give me the same error. 

Yet, the Managedcuda simpleCUBLAS example is working just fine. The only difference I notice so far comparing with my application, is the .NET Framework is at 4.5.2, while mine is at 4.6.2. But after building my app in 4.5.2, the error still remain.
![image](https://user-images.githubusercontent.com/17182101/125398082-d988c080-e37c-11eb-80cc-36533dcc01f8.png)

Obviously, base on the error message, this file "cublas64_11.dll" is missing when the wrapper is calling the native function. I'm able to locate this file at the NVDIA Toolkit folder, but since it is a Cuda C/C++ dll, I can't directly add it to my C# reference. Any insights from you would be much appreciated! 
![image](https://user-images.githubusercontent.com/17182101/125405696-fd9ccf80-e385-11eb-94b8-2efe4b24bd06.png)

**Comment by kunzmi** [comment]
Given that the sample is running, I bet that your application is running in 32-bit and can't load the 64-bit cublas-DLL. If you are in ```Any CPU```-mode, check in the project settings that the ```prefer 32-bit``` option is not set. In case you're in ```x86-32-bit``` mode, well change to x64.

**Comment by chenw11** [comment]
Thanks for the quick response. In fact, I believe my app is already run in 64-bit, and this is the config from the Build setting, which is basically the same as the example's.
![image](https://user-images.githubusercontent.com/17182101/125469164-b3b94e70-26a4-4728-b2b2-ad727cbcfa71.png)

**Comment by kunzmi** [comment]
Then it can only be that your ```PATH``` environment variable doesn't contain the correct path to the CUDA libraries, e.g. ```C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;``` (or that the corresponding CUDA toolkit is not installed, but from your screenshot it seems to be there). When you do ```echo %PATH%``` in a console, check that the CUDA toolkit version you want to use actually appears, also that the ```PATH``` variable content is not too long, I think there's a limit of characters...

**Comment by chenw11** [comment]
Just to to share some new finding here. I was able to replicate this similar error by replacing the CUFFT.dll from 11.0.43 to 8.0.13. So it seems like it is a build version compatibility problem?
![image](https://user-images.githubusercontent.com/17182101/125529247-f0350d6b-3cad-446f-837c-4662f397e208.png)

**Comment by chenw11** [comment]
Hi Kunzmi,
I tried add the Cuda 11 DLL path to the enviroment, and the now the CUDA path is showing up in the `echo %path%`, but I 'm still getting the same error. One wired thing I found is that, ManagedCuda exmaple's SimpleCublas works at both 8.0.13 and 11.0.43 with any version of ManagedCuda, and if I setup a test case with only the cublas handle, this error pops out. Howeve, if I replace the example with your SimpleCublas codes, everything works fine. It almost looks like a run time error, but I can't find which go wrong.
![image](https://user-images.githubusercontent.com/17182101/127104050-0dec0048-4bf2-4f02-82ed-bdbbffc5c5e1.png)

A simple Cublas Handle test case
![image](https://user-images.githubusercontent.com/17182101/127106199-f49e2802-0ff0-4c1a-ab10-bb1685686f78.png)

**Comment by kunzmi** [comment]
Hi,
I'm a bit confused of what versions you actually exchanged and tested, but managedCuda and CudaBlas (the wrapper for cublas) must be of the same version targeting one specific CUDA toolkit version. If all are from the same version, it should run smoothly. The .net framework shouldn't have any influence on this. 
But looking at the length of your %PATH% variable, are you sure that this is less then 2048 characters? (If I remember correctly that is the maximum allowed length on a Windows system).
A simple test for this is, if you just copy the original Nvidia DLL of the correct version just directly in the folder of application together with the managedCuda DLLs. If it then runs, then your PATH is messed up.

**Comment by chenw11** [comment]
Hi Kunzmi,
Thank you very much for your insight. I have gone ahead to check the length of my PATH and it is less than 2048 (otherwise it won't let me add more variables). I even move the NVDIA CUDA 11.0 path to the first place but it still doesn't help to resolve this problem. I also found "cublas64_11.dll" is already in my bin folder, but when my app runs it still couldn't find it. 
![image](https://user-images.githubusercontent.com/17182101/127350950-0cdf0445-ab1a-4842-836d-2b0768ee4206.png)

**Comment by chenw11** [comment]
I want to share a good news after weeks of debugging. This BUG is resolved if I initialize the `cublas `handle in my Main program.  Since I'm developing a Window Form Application, so it I'm initializing this object in the `Main{} `scope. 
![image](https://user-images.githubusercontent.com/17182101/127910005-b29d06b6-2860-4f1c-bccd-772d98b9b530.png)
However, this is a dummy handle that will not be used in the main class though, because I'm using a separated object in multi-thread to handle all the GPU codes. But to avoid this "cublas64_11.dll" missing error, at least this is the only work around I found. I hope this help the others in the future.
