### ISSUE TITLE
Cross-platform .NET Core support

### ISSUE THREAD

**Issue by david-poirier-csn** [kunzmi/managedCuda#13]
Great library! I'm pretty sure the answer is "no", but is it possible for this to be a cross-platform .NET Core library? I guess it would look for DLL files on Windows, SO files on Linux, etc?

**Comment by kunzmi** [comment]
I'm not sure if .NET Core is able to automatically load the correspondent .so files instead of the .dll, but with mono this works out of the box if you add the Linux config files into the same directory. You can find the config files in the current release section of managedCuda.

**Comment by david-poirier-csn** [comment]
That's great, thanks!
