### ISSUE TITLE
GetConvolutionBackwardFilterAlgorithm & friends not showing up on Intellisense

### ISSUE THREAD

**Issue by mrakgr** [kunzmi/managedCuda#14]
At first I thought the GetConvolution* class methods weren't in source, but after checking I see that they are there. They show up in NativeMethods, but not in the context class.  I am using the context class from F#. I'll give it a shot from C# and try disassembling the .dll if that fails.

Edit: Nope, I do not see it from C# either. I'll try [dnSpy](https://github.com/0xd4d/dnSpy).

**Comment by mrakgr** [comment]
I can confirm that the functions are not showing up in the disassembled .dll either.

Is the cuDNN on Nuget out of date or something? I'll try compiling it tomorrow.

**Comment by mrakgr** [comment]
I can confirm that when I build it manually, the missing class methods get inserted as one would expect.

I would recommend taking a look at the Nuget package as there is something wrong with cudaDNN currently.

**Comment by kunzmi** [comment]
That's why CudaDNN is only a beta, if not even an alpha release :) And the repository is newer than the Nuget release.
CudaDNN is also not up to date with the current CUDNN release, I planned to catch up with the upcomming Cuda 8.0 release, but NVidia is taking some more time with this. Maybe I'll find the time to squeeze it in before Cuda 8.0. I'll have to see that...

**Comment by mrakgr** [comment]
The thing about v4 of cuDNN is that it is already out of date due to the new algorithms [from Nervana](http://www.nervanasys.com/winograd/). The Winograd algorithms will get included in the v5 of the cuDNN library. I am not sure whether saying that would make you more or less motivated to work on v4.

By the way, thanks for making ManagedCuda. I made a [small AD library](https://github.com/mrakgr/Spiral-Library) using it and am currently making a [much improved version](https://github.com/mrakgr/Spiral-V2) with a focus on convolutional nets. I definitely could not have done it without it.

**Comment by mrakgr** [comment]
I am considering doing the wrapper for v4 myself now. v3 is unbelievably buggy.

Just now the GetConvolutionBackwardDataAlgorithm gave me back an algorithm for which the GetConvolutionBackwardDataWorkspaceSize threw an exception. This is unbelievable.

I want to ask, did you use some tool to strip the information from cudnn.h or did you do it by hand? The later seems unlikely given that you did NPP. 

I'll give it a bit more with v3 and then do some community service if this really turns out to be a library bug. I do not want to write a parser for cudnn.h if some tool already exists though.

**Comment by kunzmi** [comment]
Any contribution is welcome, especially for CUDNN which I'm not really using myself. Whatever (even partial) extension you can contribute can easily be merged to the repository.
For npp I have some substanitial help from a little parser for the h-files, especially the documentation comments. But that parser is to hardcoded specifically for npp, why cudnn is all done by hand so far...

**Comment by mrakgr** [comment]
I've [started work](https://github.com/mrakgr/managedCuda) on the wrapper and just finished going through `cudnn.h` and `NativeMethods.cs`. The new batch normalization functions have a lot of void* arguments, so I will have to finish the rest and play around with them in order to figure out what the actual types are. Give me a few days/week and I'll get this done.

**Comment by mrakgr** [comment]
Currently I am trying to make the batch normalization functions work. While I was hard at work on that it seems that the [v5 release candidate] of cuDNN just came out. I'll do it as well when I am done with this.
