### ISSUE TITLE
Requesting feedback on the pull request

### ISSUE THREAD

**Issue by mrakgr** [kunzmi/managedCuda#19]
Hello, it has been a month since I made the pull request and I have still not received any feedback from you. Have you been too busy to respond, or did the pull request slip through the cracks? I need to know. Thanks.

**Comment by kunzmi** [comment]
Good that you remind me! I'm sorry, I was very busy the past weeks and totally forgot about that. I'll try to merge it ASAP!
From what I've seen, the _v5 variant can be used as is, I'll keep you posted the next days.

Cheers,
Michael
