### ISSUE TITLE
CudaDNN not a part of the solution/NuGet package

### ISSUE THREAD

**Issue by MikulasZelinka** [kunzmi/managedCuda#2]
Hello,

CudaDNN is not a part of the ManagedCuda solution and consequently not a part of the NuGet package. Do you think it would be possible to add CudaDNN to the solution or is it excluded on purpose? :)

Thank you very much!

**Comment by kunzmi** [comment]
Hi,

CudaDNN is excluded on purpose as you need to be a registered developer at Nvidia in order to obtain the original library. The release cycle of cuDNN is also not cuppled to Cuda, as is the case for example for CUFFT or NPP. That's why CudaDNN is only availale in the repository and not in the managedCuda release on NuGet.

Michael

**Comment by MikulasZelinka** [comment]
What about making a separate (optional) NuGet for CudaDNN then? I think it would help greatly and there are some projects that approach the problem in a similar way (they have optional NuGet packages for subprojects with limited availability or additional dependencies).

**Comment by kunzmi** [comment]
You're right, it might be a good idea to create an additional NuGet package. To be honest, I didn't expect such an impact of CudaDNN when I added it to the repository as the usual frameworks like theano or caffe are not made for .net, but many people want it. I'll see how to fix this and will let you know...

**Comment by MikulasZelinka** [comment]
Thank you very much, greatly appreciated! :)

**Comment by kunzmi** [comment]
You'll find a new package on Nuget named ManagedCuda-CudaDNN. Please also keep in mind, that the CudaDNN library is not as well tested as the other parts of managedCuda, thus don't rely on it for production code!
