### ISSUE TITLE
Array Indexing error

### ISSUE THREAD

**Issue by lorenzoviola** [kunzmi/managedCuda#21]
Hello

I'm having from some days a struggle with NPPImage_8uC1 pixel indexing.

I've uploaded the following project : 

[ManagedCudaConsoleTestNPP2.zip](https://github.com/kunzmi/managedCuda/files/312239/ManagedCudaConsoleTestNPP2.zip)

it's a console application, with the following code in a class for testing :

using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Reflection;

using ManagedCuda;
using ManagedCuda.NPP;
using ManagedCuda.NVRTC;
using ManagedCuda.VectorTypes;

namespace ManagedCudaConsoleTestNPP
{
    class Program
    {
        static void Main(string[] args)
        {                  
            var ctx = new CudaContext(CudaContext.GetMaxGflopsDeviceId());

            string src =
            @"extern ""C"" {
                __global__ void TestNPPKernel(
		            unsigned char* input,unsigned char *output,
		            int width, int height,
		            int colorWidthStep, int grayWidthStep)
	            {
		            int tx = blockIdx.x * blockDim.x + threadIdx.x;
		            int ty = blockIdx.y * blockDim.y + threadIdx.y;

	                if (ty < height && tx < width)
                    {
		                int color_tid = ty * colorWidthStep + tx;

		                unsigned char blue = input[color_tid];
		                unsigned char green = input[color_tid + 1];
		                unsigned char red = input[color_tid + 2];

		                float gray = red * 0.298912f + green * 0.586611f + blue * 0.114478f;

                        int gray_tid = ty * grayWidthStep + tx;
		                output[gray_tid] = static_cast<unsigned char>(gray);
                    }
	            }
            }";

            //compile to ptx and prepare kernel
            var compiler = new CudaRuntimeCompiler(src, "TestNPPKernel.cu");
            compiler.Compile(null);
            byte[] ptx = compiler.GetPTX();

            var kernel = ctx.LoadKernelPTX(ptx, "TestNPPKernel");

            //initialize kernel and bitmaps
            kernel.GridDimensions = new dim3(128, 16, 1);
            kernel.BlockDimensions = new dim3(16, 8, 1);

            int nFrameWidth = 2048;
            int nFrameHeight = 128;

            var bmp_original = new NPPImage_8uC3(nFrameWidth, nFrameHeight);
            var bmp_gray = new NPPImage_8uC1(nFrameWidth, nFrameHeight);

            var bmpCol = new Bitmap(nFrameWidth, nFrameHeight, PixelFormat.Format24bppRgb);
            var bmpGray = new Bitmap(nFrameWidth, nFrameHeight, PixelFormat.Format8bppIndexed);

            //fill bitmap with red, green, blue, cyan, magenta, yellow pixels
            var colR = Color.FromArgb(255, 0, 0);
            var colG = Color.FromArgb(0, 255, 0);
            var colB = Color.FromArgb(0, 0, 255);
            var colC = Color.FromArgb(0, 255, 255);
            var colM = Color.FromArgb(255, 0, 255);
            var colY = Color.FromArgb(255, 255, 0);

            for (int x = 0; x < nFrameWidth / 6; x++)
            {
                for (int y = 0; y < nFrameHeight; y++)
                {
                    bmpCol.SetPixel(x * 6 + 0, y, colR);
                    bmpCol.SetPixel(x * 6 + 1, y, colG);
                    bmpCol.SetPixel(x * 6 + 2, y, colB);
                    bmpCol.SetPixel(x * 6 + 3, y, colC);
                    bmpCol.SetPixel(x * 6 + 4, y, colM);
                    bmpCol.SetPixel(x * 6 + 5, y, colY);
                }
            }

            bmpCol.Save("input.png");

            //copy to cuda device and launch kernel
            bmp_original.CopyToDevice(bmpCol);

            kernel.Run(
                bmp_original.DevicePointer, bmp_gray.DevicePointer,
                bmp_original.Width, bmp_original.Height,
                bmp_original.Width * 3, bmp_gray.Width);

            bmp_gray.CopyToHost(bmpGray);

            //correct palette to gray colors
            var cpGray = bmpGray.Palette;

            for (int i = 0; i < 256; i++)
                cpGray.Entries[i] = Color.FromArgb(i, i, i);

            bmpGray.Palette = cpGray;

            bmpGray.Save("result.png");
        }
    }
}

This application will compile a kernel that should make a RGB to Gray conversion, fill a bitmap, 
launch the kernel and via NPP get the output bitmap "bmpGray"

What is happening to me (of course i'm doing something wrong, but I've tried many different datatypes !!) is that the output looks always misaligned

I'm filling a NPPImage_8uC3, and I want to receive a NPPImage_8uC1

I'm using arrays made of "unsigned char"

Maybe this is a wrong choice, I've tried many others, but without luck.

What I need to achieve is to be able to use at the same time NPP primitive funcions and my ".cu/kernel" sources.

Could you please help ? Suggesting the better parameters types to use , or providing a working example, that starts from a 24bpp image and returns a 8bpp (gray) image, using NPP (not the ColorToGray function) and kernel launch ?

I would really understand what I'm doing wrong.

Thank you for any help.

Best Regards

**Comment by kunzmi** [comment]
Hi,

two things are wrong in your code:
1) To index in the color image inside your kernel, you need to multiply `tx` by 3 (for the three RGB values). So `int color_tid = ty * colorWidthStep + tx;` gets `int color_tid = ty * colorWidthStep + tx * 3;` 
2) That what you call "WidthStep", in NPP this is refered to as "Pitch", in System.Drawing.Bitmap this would be a "Stride", is not per se the width of the image times the pixel size in bytes. NPP usually appends some additional bytes  so that every line starts at a "good" address in memory to increase memory throughput. So instead of `kernel.Run(
            bmp_original.DevicePointer, bmp_gray.DevicePointer,
            bmp_original.Width, bmp_original.Height,
            bmp_original.Width * 3, bmp_gray.Width);`
you write `kernel.Run(
            bmp_original.DevicePointer, bmp_gray.DevicePointer,
            bmp_original.Width, bmp_original.Height,
            bmp_original.Pitch, bmp_gray.Pitch);` 
and you'll get your image nicely transformed.

Cheers,
Michael

**Comment by lorenzoviola** [comment]
Wow ! great reply !

1) I forgot to add on the code I sent (tx*3) : It was one of the many tries, which get lost =P

2) I really need to study better that "pitch"... (I really would change the first letter, as a newbie I loose about a week on this problem !!)....  maybe it's also called padding ?

3) so "unsigned char" was a good choice ? Or in your experience other datatypes are preferred ?
On other samples on internet I see a lot of variability (int, float, char, char3, char4, uchar, and so on...)

4) Maybe there are other / better objects to use to perform image processing with managedcuda and NPP ? such as CudaArray2D , CudaLinearTexture2D, CudaSurfObject and so on ?
Too bad I couldn't find any document or sample on internet, and I couldn't undestand the benefits of one approach to the other.
I'm looking for the better possible performance, maybe the base array is the fastest choice ?


By the way, You are a real magician !
Thanks a lot for your great library and support !

**Comment by kunzmi** [comment]
Hi,
the “pitch” or “stride” is the width of one image line plus the necessary padding to get to the first pixel of the next line. So talking of padding is not wrong, but not entirely true neither as the pitch is made of both, real width and padded bytes.
The type unsigned char seems right. The counter part of unsigned char in cuda/C++ would be byte in C#. char without unsigned in cuda gets a sbyte, a signed byte. Uchar3 would be an alternative as it packs three unsigned chars together, you herewith keep the logic of a pixel. Using uchar3 you can load and address three bytes as one value. Speed wise it wouldn’t make any difference, as 3 bytes can’t be used as one bigger chunk. I guess the load of one uchar3 will be translated by the compiler to three loads of a single byte. It would make a difference if you had 4 values and an uchar4, as these types get well aligned in memory and can be fetched at once by the GPU.
Memory allocated with NPP is identical to CudaPitchedDeviceVariable<> in managedCuda for raw memory allocations and are fully interoperable. Whereas CudaArrays are different and mostly used in combination with DirectX/OpenGL interop and 3D textures. Textures and Surfaces are then again a different story. In short: You can read data directly from memory (with L1 cache), or you can read data through a different path with better caching strategies and the capability to read data linearly interpolated between two points. That would be textures and if you want to write to textures you need surfaces. But this is a very brief description :-)
Have a look at the release section of the managedCuda project here on GitHub. You’ll find a zip-file there with some samples from the original SDK ported to C#; Including some basic NPP examples.

Cheers,
Michael

**Comment by lorenzoviola** [comment]
Hi !

1) About the uchar / uchar4 choice : I'll make trials with NvidiaVIsualProfiler by these days, to choose the best for my case. I mean : I want the best performance, and the longest time is the "copy-to-device" phase.

Transferring uchar4 data (so with 25% of data transfered not useful, at least by now) could be not a good choice, If I don't get a real speed boost on CUDA calculations later.

I would like the uchar4 choice, so to write algorithm always valid for every case, but I could be restricted by the bitmap transfer.


2) I don't think I will go on the texture/surface way, as I doing these newbie steps on a image processing, where I need to access data from the bitmap, pre-process it and make calcultations, but I don't think I will need texture and surfaces features (typical for 3d or videogame apps)


3) I'm thinking about a blob-counter algorithm in cuda : did you ever find one ?

4) if not, I think I will have to try a different labeling way (i mean, different from cpu existing code) : as the bitmap/array is split in blocks/grids, what happens to blobs that are "middle-way" between the blocks-grids ?
Maybe I can try to make more iterations (about 3 ?) shifting the blocks-grids of a 25%, and then reconnecting / intersecting the results of every iteration...
What do you think ? could it be a feasible way ? 


Or maybe, there is some more "graphic" way (without labeling) to calculate centroids and areas, as described here : 

https://developer.nvidia.com/gpugems/GPUGems3/gpugems3_ch26.html

5) I really didn't noticed the release area ! I think you should place a link on your homepage, it would make your library even more useful to newbies like me =)


Thank you again !
Cheers, Lorenzo
