### ISSUE TITLE
RGB To HLS - strange byte conversion

### ISSUE THREAD

**Issue by lorenzoviola** [kunzmi/managedCuda#22]
Hello
I'm struggling again, and found no reason to the following problem...

When using NPP and doing an RGB to HLS conversion, described on page 519 of 
http://docs.nvidia.com/cuda/pdf/NPP_Library.pdf

Example : If I try to convert a bitmap filled with cyan pixels, where
(R:0 G:255 B:255) means (H:50% S:100% L:50%),
reading converted data I should read (H:127 L:127 S:255) as the NPP scale is on a 255-value.

Instead I get : H042.L127.S255....... which seems 1/3 of 127....

Please have a look to my attached project...

I really cannot find a sense to the output values

Could you share some light ?

Thank you !

[ManagedCudaConsoleTestNPP3.zip](https://github.com/kunzmi/managedCuda/files/333304/ManagedCudaConsoleTestNPP3.zip)

**Comment by kunzmi** [comment]
`System.Drawing.Bitmap` saves its pixels in BGR order in memory: Copying such an image to `NPPImage_8uC3` still keeps this BGR order but `RGBToHLS` expects RGB. Your input color is therefore not cyan but yellow...

**Comment by lorenzoviola** [comment]
Hello
I was hoping for such a reply !

I made many trials, and still wasn't sure about the BGR order in System.Drawing.Bitmap

A newbie solution for a newbie question..........=P

Thanks again !
