### ISSUE TITLE
NVRTC - architecture

### ISSUE THREAD

**Issue by lorenzoviola** [kunzmi/managedCuda#23]
Hello Michael !

I'm using your NVRTC module, and I cannot find a way to compile at runtime setting up the "code generation" parameters (ex. : "compute_20,sm_20" or  "compute_50,sm_50" )

Is it possible ? Having this setting will give any difference on the results ?

Thank you !

**Comment by kunzmi** [comment]
Hi,

the compile method takes the options as a string array: so every option you want to use for compilation is an entry in the array. E.g. `myCompiler.compile(Compile(new string[] {"--gpu-architecture=compute_20" });)` would compile your code to ptx with compute capability 2.0. See also the entire list of options at [NVRTC](http://docs.nvidia.com/cuda/nvrtc/index.html#group__options).

Cheers,
Michael

**Comment by lorenzoviola** [comment]
Hello looks like is working like a charm =)

Thank you !
