### ISSUE TITLE
NVML: unnecessary reference to ManagedCuda.csproj

### ISSUE THREAD

**Issue by mgravell** [kunzmi/managedCuda#30]
I noticed (when trying to build NVML) that it includes a reference to `ManagedCuda`. However, this is only used to satisfy some unused `using` directives. If you remove the additional directives and the reference, it builds fine. Would be happy to submit as a PR, but wanted to see if it was intentional first.

**Comment by kunzmi** [comment]
I first planned to build a managedCuda like API around the original one, but time is missing for that and other things have way more priority right now. I'm not sure if the reference is needed for some basics type definitions like SizeT if one would create the API one day...

**Comment by kunzmi** [comment]
Reference is removed...
