### ISSUE TITLE
Exception when using NPP example

### ISSUE THREAD

**Issue by aerophilic** [kunzmi/managedCuda#32]
When trying to use the NPP example on the main readme, I keep getting a:
An unhandled exception of type 'System.DllNotFoundException' occurred in NPP.dll

Additional information: Unable to load DLL 'npps64_75': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Is this a dll that wasn't included in either the library and/or in the NuGet?

**Comment by kunzmi** [comment]
NPP.dll from managedCuda is only a .net wrapper for the different native npp*.dll's from Nvidia. In order to get the libraries you need to install the Cuda toolkit, in your case version 7.5: [https://developer.nvidia.com/cuda-toolkit-archive](https://developer.nvidia.com/cuda-toolkit-archive)
