### ISSUE TITLE
Do you have Examples?

### ISSUE THREAD

**Issue by RussianDragon** [kunzmi/managedCuda#36]
Hello.
Do you have examples solutions?
I try using your library, but I had runtime exception.

DriverAPINativeMethods.cuInit(ManagedCuda.BasicTypes.CUInitializationFlags.None);
CudaDeviceVariable<int> windowSize = new CudaDeviceVariable<int>(5);

ErrorInvalidContext: This most frequently indicates that there is no context bound to the current thread. This can also be returned if the context passed to an API call is not a valid handle (such as a context that has had cuCtxDestroy() invoked on it). This can also be returned if a user mixes different API versions (i.e. 3010 context with 3020 API calls). See cuCtxGetApiVersion() for more details.

What should I do?

**Comment by kunzmi** [comment]
You can find several examples in the Samples folder in the repository. For more (general) information about the needed Cuda context, read chapter H.1 in the Cuda programming guide. In short: You need an active Cuda context per device bound to a CPU-thread in order to use the GPU with Cuda.
