### ISSUE TITLE
NPP Extension Method For DivCRev missing for double

### ISSUE THREAD

**Issue by cudaLang** [kunzmi/managedCuda#39]
The NPP extension method for DivCRev is not included for a device variable of type double.

**Comment by cudaLang** [comment]
http://docs.nvidia.com/pdf/NPP_Library_Signal.pdf  does not include the DivCRev for double.  Is it just missing or is there a work around like an NPP work around like a negative power function.

**Comment by kunzmi** [comment]
There are some trivial functions missing in NPP as I also find from time to time. In such a case I'd file a feature request to the NPP team. In the time being the simplest and fastest way to work around is to write a small kernel on your own that does exactly the operation you need.
