### ISSUE TITLE
Wrap cuDeviceGetCount()

### ISSUE THREAD

**Issue by keldor314** [kunzmi/managedCuda#4]
cuDeviceGetCount() is rather important for creating contexts when you want to support multiple devices.  You have no idea how many GPUs your user has plugged in!  Using the method from DriverAPINativeMethods is of course clunky, since you're going to then have to deal with cuInit() most of the time.

Is there any chance of adding a proper DeviceGetCount() function to the managed API?

From:

     static member Contexts =
        let devCount = ref 0
        DriverAPINativeMethods.cuInit(CUInitializationFlags.None) |> ignore
        DriverAPINativeMethods.DeviceManagement.cuDeviceGetCount(devCount) |> ignore
        //Error handling??!
        [|
            for n in [0..!devCount-1] do
                yield new CudaContext (n)
        |]

To:

    static member Contexts =
        [|
            for n in [0..DeviceGetCount()-1] do
                yield new CudaContext (n)
        |]

**Comment by kunzmi** [comment]
The `CudaContext` class has a static method `GetDeviceCount()` that does exactly what you want to have^^

**Comment by keldor314** [comment]
It does?  I guess I overlooked it.  Neat!
