### ISSUE TITLE
thrust and managedcuda

### ISSUE THREAD

**Issue by lorenzoviola** [kunzmi/managedCuda#46]
Hello Michael

I see that this issue is closed :
https://github.com/kunzmi/managedCuda/issues/10

but I try anyway...

Anything changed about thrust since Jan 2016, with cuda 8.0 ?

it would be great to be able to run kernels with Thrust included directly from ManagedCuda

Any hope on this side ?
If so, do you have any working sample of ManagedCuda with thrust ?

I'm trying to run this particular kernel :

https://github.com/thrust/thrust/blob/master/examples/bounding_box.cu

without any luck

Best Regards

**Comment by kunzmi** [comment]
No, unfortunately nothing has changed. Thrust is a header library that needs to be compiled by nvcc and is tightly bound to C++ host code.
One might think of starting a similar library for .net, but this is way out of scope for managedCuda. If you need a specific kernel you can try to separate it from its surroundings and compile it to ptx, the host part then needs to re-implemented in C#.

**Comment by lorenzoviola** [comment]
ok michael, thanks anyway !
