### ISSUE TITLE
Allocating a CudaPitchedDeviceVariable using a width and height throws an ErrorInvalidValue exception.

### ISSUE THREAD

**Issue by dennisai** [kunzmi/managedCuda#47]
Hello,

When I try to execute the following code, I get an ErrorInvalidValue exception.

    CudaContext cudaContext = new CudaContext(CudaContext.GetMaxGflopsDeviceId());
    CudaPitchedDeviceVariable<ushort> var = new CudaPitchedDeviceVariable<ushort>(
        2048, 160);

I have tried with multiple parameters, such as `(16, 16)` for my width and height.  It appears to work with `float` but not with `ushort`.  Any idea why it doesn't support `ushort`?

**Comment by RoBiK75** [comment]
Please see the CUDA Device API documentation: http://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gcbe9b033f6c4de80f63cc6e58ed9a45a

> ElementSizeBytes may be 4, 8 or 16 (since coalesced memory transactions are not possible on other data sizes).

**Comment by dennisai** [comment]
Great thank you RoBik75!
