### ISSUE TITLE
Support jagged array？

### ISSUE THREAD

**Issue by craigtao** [kunzmi/managedCuda#48]
thanks ManagedCUDA Opensource.

I have question. " ManagedCUDA Support C# jagged array" ?

thank you

craig tao

**Comment by kunzmi** [comment]
Please see my answer on [stackoverflow](https://stackoverflow.com/questions/44163375/c-sharp-managedcuda-2d-array-to-gpu/) for the same question.

**Comment by craigtao** [comment]
thank you very much. i can do like this in project?
