### ISSUE TITLE
Driver version?

### ISSUE THREAD

**Issue by NeuralDip** [kunzmi/managedCuda#53]
Hi, 
i am using CudaContext.GetDeviceInfo() to get the driver info among other things, but for 'DriverVersion' i get a 9.0. Not a 22.21.13.8541 nor a 385.41. am i looking the wrong place?

**Comment by kunzmi** [comment]
`CudaContext.GetDeviceInfo()` calls `cuDriverGetVersion()` to get the driver version, which indeed returns the Cuda version number of the installed driver and not the driver version itself.
As far as I know, there's no way to determine the exact driver version (e.g. 385.41) using the Cuda API. But if you really need that version number you can use NVML-library (also part of managedCuda but only in a very rudimentary way...) and use `nvmlSystemGetDriverVersion()`.

**Comment by NeuralDip** [comment]
ok thanks
