### ISSUE TITLE
The description for amax is wrong.

### ISSUE THREAD

**Issue by mrakgr** [kunzmi/managedCuda#6]
Inside the function description it says that it uses C (zero based) indexing, but in fact it uses the Fortran indexing. This matches the description on [cuBlas programming guide](http://docs.nvidia.com/cuda/cublas/#cublasi-lt-t-gt-amax) where it says that it uses Fortran indexing. amin is also similarly broken. I would recommend just fixing the description. The NPP Min and Max functions use C based indexing in contrast to the cuBlas ones.

**Comment by kunzmi** [comment]
You're right, wondering where this error came from, even the first cublas release was Fortran like...
I'll change it once I have access to my computer

**Comment by mrakgr** [comment]
Fixed in the latest pull request.
