### ISSUE TITLE
NPPImage_8uC1.Resize 

### ISSUE THREAD

**Issue by AeroClassics** [kunzmi/managedCuda#62]
For some reason the Resize function requiring 4 parameters is commented out. Is there a different way to resize an image?

Thanks,
Doug

**Comment by kunzmi** [comment]
Resize got removed by Nvidia in some Cuda version and then was re-introduced again later on. Likely you just have the version where it's missing…

BTW: Everything updated to Cuda 10

**Comment by AeroClassics** [comment]
Thanks, Michael!
