### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AeroClassics** [kunzmi/managedCuda#63]
I download the master zip file, unzipped it and went compile on Windows 10, VS 2017, and the project file references CudaGraph.cs and CudaGraphExec.cs in ManagedCuda but the files are not in the repository. This is also true for CudaSparse. 
I removed the missing files from the project buit it still does not compile so I am going to assume these files are needed.

Thanks,
Doug

**Comment by kunzmi** [comment]
only forgot to add them to the repository… I added them now

Best,
Michael

**Comment by AeroClassics** [comment]
Thank you!

Best Regards / Mit freundlichen Grüßen,
Doug


[cid:image001.png@01D3D5F5.7EE2C150]

Douglas R. Jones
Sr. Software Engineer/AdVISE Project Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Parkway Ste 100
Flower Mound, TX 75028
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com<mailto:Doug.Jones@rsa.rohde-schwarz.com>
Website: http://www.rohde-schwarz.com/
