### ISSUE TITLE
nuget is not working for me

### ISSUE THREAD

**Issue by AeroClassics** [kunzmi/managedCuda#7]
I have tried both the 7.5 standalone and x64 versions and I get the following error:
![image](https://cloud.githubusercontent.com/assets/14000868/12176652/0aad4ca4-b52e-11e5-9e9d-7696a7a8092b.png)

It leaves a packages.config file but VS2013 never tries to get the package when I build. The package.config file looks like this:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="ManagedCuda-75-Standalone" version="7.5.7" targetFramework="net45" />
</packages>

Not being an expert with the inner workings of VS and its interaction with nuget I am not sure what is going on. In the NuGet Cache I do see both packages.

Thanks!
Douglas R Jones

**Comment by kunzmi** [comment]
Have you removed all the manual references to managedCuda first? The packages should be referenced as you install them / add them with Nuget. Have you tried other nuget packages to see if it is a general nuget problem?

**Comment by AeroClassics** [comment]
Hi,
Actually I did and it seems there may be a nuget problem. I have pulled 
the latest nuget from nuget.org and I am going through thesolution and 
ensuring that there are no references to managedCuda and no package 
folders around. I am just about done with that and I will give it a shot.

Best Regards, 
Doug





 
Douglas R. Jones
Sr. Software Eng./AdVISE Product Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Pkwy.
Suite 100
Flower Mound, TX 75238
, 
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com
Website: http://www.rohde-schwarz.com/

**Comment by AeroClassics** [comment]
Michael,
Cleaned everything off and tried from the PM console. I get this:



Something is definitely screwy.


Best Regards, 
Doug





 
Douglas R. Jones
Sr. Software Eng./AdVISE Product Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Pkwy.
Suite 100
Flower Mound, TX 75238
, 
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com
Website: http://www.rohde-schwarz.com/

**Comment by kunzmi** [comment]
Sorry, can't see what the error is. Can you post it again as text?

**Comment by AeroClassics** [comment]
Fixed and working. Turns out it is a bug in NuGet. Running this command 
regsvr32 "C:\Program Files (x86)\Common Files\microsoft 
shared\MSEnv\VsLangproj.olb" fixed the problem

Best Regards, 
Doug





 
Douglas R. Jones
Sr. Software Eng./AdVISE Product Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Pkwy.
Suite 100
Flower Mound, TX 75238
, 
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com
Website: http://www.rohde-schwarz.com/
