### ISSUE TITLE
Crop NPP image

### ISSUE THREAD

**Issue by serjl** [kunzmi/managedCuda#78]
Hello kunzmi,

I was trying to crop an NPP Image  NPPImage_8uC1 src by the following code:

src.SetRoi(nppRect);
NPPImage_8uC1 dest= new NPPImage_8uC1(nppRect.width, nppRect.height);
dest.CopyToDevice(scr.DevicePointerRoi, dest.Pitch);

dest.CopyToHost(bitmap);
As a result the bitmap is corrupted - kinda wrong pitch - pixels are spread wrong . 

I guess I'm using CopyToDevice wrong. 

What is the best and short way to crop the NPP image on GPU.
(Of course I can write a kernel and run it).
Can you please consult in the issue.
 Thank you a lot in advance.

**Comment by kunzmi** [comment]
`dest.CopyToDevice(scr.DevicePointerRoi, dest.Pitch)` -> use the `src.Pitch` as argument.
Or simply use `src.Copy(dest)`, that one handles all ROI settings.

Notice also, that if you want to copy the final image to a bitmap of different size you have to use CopyToHostRoi.

**Comment by serjl** [comment]
Thank you very much for a quick reply. With both commands you proposed i am getting just black image. I checked the image itself is ok, i can copy it to a bitmap from the device normally.

**Comment by serjl** [comment]
Thanks a lot for a quick reply!
dest.CopyToDevice(scr.DevicePointerRoi, src.Pitch) works nice as expected.
src.Copy(dest) gives a black image.
