### ISSUE TITLE
Specifying nested streams depth limit using cudaLimitDevRuntimeSyncDepth

### ISSUE THREAD

**Issue by velaris1** [kunzmi/managedCuda#81]
Hi,

I'm running a kernel that leverages nested kernel launches through streams. It seems that the current max depth supported by my device (1080 Ti)  is 16, whereas the documentation specifies 24 as being the limit:

"The overall maximum nesting depth is limited to 24, but practically speaking the real limit will be the amount of memory required by the system for each new level (see Memory Footprint above). Any launch which would result in a kernel at a deeper level than the maximum will fail. (...)"

It goes on to say that:

" This maximum synchronization depth (and hence reserved storage) may be controlled by calling cudaDeviceSetLimit() and specifying cudaLimitDevRuntimeSyncDepth."

I'd like to try setting a new depth of 24, hoping that my limit is not memory-bound.

I could not find a way to configure this option through Managed Cuda. Did I miss it ?

I'm using ManagedCuda 10.0

Thanks

**Comment by velaris1** [comment]
Closing the issue for now. It seems like I was using an old version of the library (ManagedCuda), upgrading to ManagedCuda 10.0 seems to have fixed it. I can now have a nested depth of 24.

**Comment by kunzmi** [comment]
CudaContext.SetLimit() is what you were looking for. On the other hand I don't see how a different managedCuda version influences that behaviour, given that all it does is calling the same native library. But as long as it works...

**Comment by velaris1** [comment]
Thank you for the reply. I definitely should have checked the methods on the CudaContext, my bad.

Not sure either, I'll double check using the old version and confirm if that's really what's affecting the nesting. Regardless, thank you for your excellent work.

**Comment by velaris1** [comment]
I'm stupid. I confused the nesting depth with the synchronization depth. It looks like the nesting depth is not set through API calls, only the synchronization depth is. My issue was related to nesting, not synchronization.

I should have paid more attention...:

"The synchronization depth is defined as the deepest level at which the program will explicitly synchronize on a child launch. Typically this is one less than the nesting depth of the program, but if the program does not need to call cudaDeviceSynchronize() at all levels then the synchronization depth might be substantially different to the nesting depth."

My apologies for the post.
