### ISSUE TITLE
CUDA 11 Support

### ISSUE THREAD

**Issue by varon** [kunzmi/managedCuda#87]
Thanks for making this awesome library. It works really well and I've run into zero issues using it!

With CUDA 11 release just around the corner and the RC currently available, getting support for CUDA 11 would be absolutely great.

I understand C#/native interop quite well, so I'm more than happy to lend a few hours to help you achieve this. `bfloat16` is probably the key feature I'm after for this. It looks very easy to implement and extremely useful to have.

**Comment by kunzmi** [comment]
I wait for the final release to be out before doing any changes. It is more time consuming to track the differences between RC and final release than doing all at once. Basically one would do the upgrade twice and in the past Nvidia made quite some changes in between RC and final release…

As for bfloat16, what I have seen so far, this is device only, so no changes on the API side apart from CUBLAS and other libraries. But even there the changes are not dramatic.

**Comment by varon** [comment]
In case you missed it, CUDA 11 is now available.

What do we need to do to support it?

**Comment by kunzmi** [comment]
ManagedCuda is now up to date with CUDA 11 ;)

**Comment by varon** [comment]
Thank you so much!

For those looking, the package seems to be here: https://www.nuget.org/packages/ManagedCuda-11/
